---
title: "Amino Acid"
author: "Richard Edwards"
date: "June 4, 2015"
output: html_document
---



```{r}
#Amino Acids                                         NH2
 #                                                   |
 #All Amino Acids have the general composition of   HC--CO2 with the 'R' group
 #                                                   |      specifying the 
 #                                                   R      amino acid residue
 
 #Defining Aromatic 'R' Groups
 Phenyl <- c("C",rep("CH",5))
 Imidazole <- c("C","CH","NH","CH","NH+")
 Indole <- c("C","CH","NH","C","C",rep("CH",4))
 Phenol <- c("C","CH","CH","C_OH","CH","CH")
 #The following will relate the 1-letter abreviation of 
 #the 20 AA residues with their respecitve 'R' groups

A <- c("CH3")                              #Alanine (Ala)
C <- c("CH2", "SH")                        #Cysteine (Cys)
D <- c("CH2","COO-")                       #Aspartate (Asp)
E <- c("CH2","CH2","COO-")                 #Glutamate (Glu)
F <- c("CH2",Phenyl)                       #Phenylalanine (Phe)
G <- c("H")                                #Glycine (Gly)
H <- c("CH2",Imidazole)                    #Histidine (His)
I <- c("Methyl_CH","CH2","CH3")            #IsoLeucine (Ile)
K <- c(rep("CH2",4), "NH3+")               #Lysine (Lys)
L <- c("CH2","Methyl_CH","CH3")            #Leucine (Leu)
M <- c("CH2","CH2","S","CH3")              #Methionine (Met)
N <- c("CH2","CO","NH2")                   #Asparagine (Asn)
P <- c("CH2","CH2","CH2")                  #Proline (Pro)
Q <- c("CH2","CH2","CO","NH2")             #Glutamine (Gln)
R <- c(rep("CH2",3), "NH", "CNH2+","NH2")  #Arginine (Arg)
S <- c("CH2","OH")                         #Serine (Ser)
T <- c("CH","OH","CH3")                   #Threonine (Thr)
V <- c("Methyl_CH","CH3")                  #Valine (Val)
W <- c("CH2",Indole)                       #Tryptophan (Trp)
Y <- c("CH2", Phenol)                      #Tyrosine (Tyr)
```

```{r}
#Classifying AA into groups

AAclassifier <- function(AA){
  
  class = data.frame(size,hydrophobic,polar,aromatic)
  n = length(AA)
 
  if(n <= 3){                   #classifier for Small
                                #and Tiny AA residues
   class$size <- "Small"     
    
   if(n < 3){
      
     class$size <-"Tiny"
   }
  }
  else{
    class$size <- ""
  }
  
  if(!is.na(match("C",AA)) == TRUE) {     #classifier for Aromaticity
    
    if(AA[match("C",AA):(length(Phenyl)+1)] == Phenyl ||
       AA[match("C",AA):(length(Imidazole)+1)] == Imidazole ||
       AA[match("C",AA):(length(Indole)+1)] == Indole ||
       AA[match("C",AA):(length(Phenol)+1)] == Phenol){
          
         class$aromatic <- "Aromatic"
    }
  }
  else{
    class$aromatic <- ""
  }

  if(){
    
    if(!is.na(match("Methyl_CH",AA)) == TRUE){  #classifierf for Aliphatic
    class$hydrophobic <- c("Hydrophobic","Aliphatic")    
    }
  }
  if(length(grep("OH|SH|+|-",AA,fixed=TRUE)) != 0
     ){ #classifier for polar
    
    class$polar = "Polar"
    
    if(!is.na(match("COO-",AA)) == TRUE){ #classifier for neg. charge
    
      class$charge <- "Charge(-)"
    }
  
    if(length(grep("+",AA,fixed=TRUE)) != 0){ #classifier for pos. charge
    
      class$charge <- "Charge(+)"
    }
  }
  return(class)
}
```

```{r}
library(selectr)
#Acquire Mutant Frequency Table
 html("http://www.abren.net/protherm/mutation.html")%>%
+ html_node("table")%>%
+ html_table(fill=T) -> aATable

#---------------------------------------------------------------------------

#Acquire Further Data
url <- "http://www.abren.net/protherm/protherm_result.php?&DISP01=1&DISP02=1&DISP10=1&DISP14=1&DISP16=1&DISP18=1&DISP19=1&DISP22=1&DISP23=1&DISP24=1&DISP26=1&DISP30=1&DISP31=1&DISP38=1&NUMBER2=3000000&SOURCE=human&MUTA-C0=on&ASA-C=0-Any&ASA3=0-%&PH1=6.8&PH2=8.2&COUNT_E2=980&COUNT_S2=0"

xp <- '/html/body/table[2]'

AASearch <- url %>%
  html() %>%
  html_nodes(xpath=xp) %>%
  html_table(fill=TRUE)
AASearch <- AASearch[[1]]
AASearch <- AASearch[-c(16:21)]
names(AASearch) <- c("Entry","Protein","Source","Mutation","dG_H2O","dG","T", "Tm","dHcal","m","Cm","pH","Measure","Method",	"REFERENCE")

#--------------------------------------------------------------------------

url<- "http://p53.iarc.fr/AAProperties.aspx"
  
xp <- '//*[@id="aapropform"]/table'

AAProp <- url %>%
  html() %>%
  html_nodes(xpath=xp) %>%
  html_table(fill=TRUE)
AAProp <- AAProp[[1]]
AAProp <- AAProp[1:(nrow(AAProp)-1),]

#---------------------------------------------------------------------------

url <- "http://www.mhhe.com/physsci/chemistry/carey5e/Ch27/ch27-1-4-2.html"

AAPI <- url %>%
  html() %>%
  html_nodes("table") %>%
  html_table(fill=TRUE)                  #generates the table from the webpage
AAPI <- AAPI[[2]]
names_AAPI <- AAPI[1,]                   #extracts the names from the first row
names_AAPI <- gsub("Â","",names_AAPI)    #removes Â characters (Å = alt 0194)
AAPI <- AAPI[2:21,]                   #extracts the amino acid data   
AAPI <- gsub("Â| ","",AAPI)             
AAPI <- gsub("\"","",AAPI)            #removes all the \'s
AAPI <- sub("c","",AAPI)              #removes the 1st c from each line
AAPI <- gsub("(","",AAPI,fixed=TRUE)  #removes all the ('s
AAPI <- gsub(")","",AAPI,fixed=TRUE)  #removes all the )'s
AAPI <- strsplit(AAPI,split=",")      #splits the character arrays
AAPI <- as.data.frame(AAPI)           #remakes the data frame/table
names(AAPI) <- names_AAPI             #replaces the name with the original
```
