---
title: "AA Sequences"
author: "Richard E"
date: "June 23, 2015"
output: html_document
---

Import source data from prior file.

```{r, echo=FALSE}
library(igraph)
library(rgl)
library(XML)
library(RCurl)
source("C:/Documents and Settings/Research/Redwards/Neural-Network-Practice/AApkg.R")
source("C:/Documents and Settings/Research/Redwards/Neural-Network-Practice/Seq_Mut_pkg.R")
source("C:/Documents and Settings/Research/Redwards/Neural-Network-Practice/UsingBio3d.R")

```

Analyzing Peptides

```{r}
Gen.Peptide <- function(AASeq){
  
  l = nchar(AASeq)  #obtain the number of residues in the sequence
  
  Peptide <- strsplit(AASeq,split="")  #convert character string into individual residues
  Peptide <- unlist(Peptide)   #ensure that there are no subgroups
 
  #locating the position of the respective residues in the sequence
  loc.A <- grep("A",Peptide); loc.C <- grep("C",Peptide); loc.D <- grep("D",Peptide)
  loc.E <- grep("E",Peptide); loc.F <- grep("F",Peptide); loc.G <- grep("G",Peptide)
  loc.H <- grep("H",Peptide); loc.I <- grep("I",Peptide); loc.K <- grep("K",Peptide)
  loc.L <- grep("L",Peptide); loc.M <- grep("M",Peptide); loc.N <- grep("N",Peptide)
  loc.P <- grep("P",Peptide); loc.Q <- grep("Q",Peptide); loc.R <- grep("R",Peptide)
  loc.S <- grep("S",Peptide); loc.T <- grep("T",Peptide); loc.V <- grep("V",Peptide)
  loc.W <- grep("W",Peptide); loc.Y <- grep("Y",Peptide)
  
  #convert 1-letter abbreviation to the atomic representation
  Peptide[loc.A] <- list(c(AABackbone, Mol2Atm(A)))
  Peptide[loc.C] <- list(c(AABackbone, Mol2Atm(C)))
  Peptide[loc.D] <- list(c(AABackbone, Mol2Atm(D)))
  Peptide[loc.E] <- list(c(AABackbone, Mol2Atm(E)))
  Peptide[loc.F] <- list(c(AABackbone, Mol2Atm(F)))
  Peptide[loc.G] <- list(c(AABackbone, Mol2Atm(G)))
  Peptide[loc.H] <- list(c(AABackbone, Mol2Atm(H)))
  Peptide[loc.I] <- list(c(AABackbone, Mol2Atm(I)))
  Peptide[loc.K] <- list(c(AABackbone, Mol2Atm(K)))
  Peptide[loc.L] <- list(c(AABackbone, Mol2Atm(L)))
  Peptide[loc.M] <- list(c(AABackbone, Mol2Atm(M)))
  Peptide[loc.N] <- list(c(AABackbone, Mol2Atm(N)))
  Peptide[loc.P] <- list(c(AABackbone[1:8], Mol2Atm(P)))
  Peptide[loc.Q] <- list(c(AABackbone, Mol2Atm(Q)))
  Peptide[loc.R] <- list(c(AABackbone, Mol2Atm(R)))
  Peptide[loc.S] <- list(c(AABackbone, Mol2Atm(S)))
  Peptide[loc.T] <- list(c(AABackbone, Mol2Atm(T)))
  Peptide[loc.V] <- list(c(AABackbone, Mol2Atm(V)))
  Peptide[loc.W] <- list(c(AABackbone, Mol2Atm(W)))
  Peptide[loc.Y] <- list(c(AABackbone, Mol2Atm(Y)))
  
  #Uncharge the first Nitrogen and convert the list back into characters
  Peptide <- c(sub("N+","N",Peptide[1:(l-1)],fixed=TRUE),Peptide[l])
  Peptide <- gsub("\"","",Peptide)
  Peptide <- gsub("(","",Peptide,fixed=TRUE)
  Peptide <- gsub(")","",Peptide,fixed=TRUE)
  Peptide <- sub("c","",Peptide,fixed=TRUE)
  Peptide <- gsub("[[:space:]]","",Peptide)
  Peptide <- strsplit(Peptide,split=",")
  
  #remove the detached Hydrogens
  Peptide[[1]] <- Peptide[[1]][c(1:6,9:length(Peptide[[1]]))] 
  
  #remove water molecules
  for(i in 2:(l-1)){
    Peptide[[i]] <- Peptide[[i]][c(1:3,5:6,9:length(Peptide[[i]]))]  
  }
  
  #remove the last charge Oxygen
  Peptide[[l]] <- Peptide[[l]][c(1:3,5:length(Peptide[[l]]))] 
  
  return(Peptide)
}

#-------------------------------------------------#
#-------------------------------------------------#

fPath.Peptide <- function(AASeq){
 
  l = nchar(AASeq)
  Peptide <- strsplit(AASeq,split="")  #convert character string into residues
  Peptide <- unlist(Peptide)
  
  Peptide.atm <- Gen.Peptide(AASeq)
  
  #Obtain the lengths of each residue
  Pep_lengths <- c()
    for(i in 1:l){
      Pep_lengths[i] <- length(Peptide.atm[[i]])
      }
  
  CTPath <- c(c(1,2,2,3,3,2,2,4),c(7,1,1,5,5,6))  #carbon terminus bondage
  
  #assign the correct bonding for the carbon terminus determined by side group
  if(Peptide[1] == "A"){
    pPep <- c(CTPath,c(1,8,8,9),c(10,8,8,11)) 
  
  }; if(Peptide[1] == "C"){
    pPep <- c(CTPath, c(1,8,8,11,11,12),c(9,8,8,10))
  
  }
  
  if(Peptide[1] == "D"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,11,11,13),c(9,8,8,10))
  
  }; if(Peptide[1] == "E"){
    pPep <- c(CTPath,c(1,8,8,11,11,14,14,15,15,14,14,16),
               c(9,8,8,10),c(12,11,11,13))
  
  }; if(Peptide[1] == "F"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,14,14,16,16,18,18,20,20,11,11,20,20,21),
               c(9,8,8,10),c(13,12,12,14,14,15),c(17,16,16,18,18,19))
  }
  
  if(Peptide[1] == "G"){
    pPep <- c(CTPath,c(1,8))
  
  }; if(Peptide[1] == "H"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,14,14,16,16,18,18,11,11,12,12,13),
              c(9,8,8,10),c(14,15),c(17,16,16,18,18,19))
  
  }; if(Peptide[1] == "I"){
    pPep <- c(CTPath,c(1,12,12,13),c(9,8,8,12,12,14,14,17,17,18),
              c(10,8,8,11),c(15,14,14,16),c(19,17,17,20))
  }
  
  if(Peptide[1] == "K"){
    pPep <- c(CTPath,c(1,8,8,11,11,14,14,17,17,20,20,23),c(9,8,8,10), 
              c(12,11,11,13),c(18,17,17,19),c(21,20,20,22),c(15,14,14,16))
  
  }; if(Peptide[1] == "L"){
    pPep <- c(CTPath,c(1,8,8,15,15,11,11,12),c(9,8,8,10),c(13,11,11,14),
              c(16,15,15,17,17,19),c(18,17,17,20))
  
  }; if(Peptide[1] == "M"){
    pPep <- c(CTPath,c(1,8,8,11,11,14,14,15,15,16),c(9,8,8,10), 
              c(12,11,11,13),c(18,15,15,17))
  }
  
  if(Peptide[1] == "N"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,11,11,13,13,14),
               c(9,8,8,10),c(15,13))
  
  }; if(Peptide[1] == "P"){
    pPep <- c(c(1,2,2,3,3,2,2,4),c(6,1,1,5),
              c(1,7,7,10,10,13,13,5),c(8,7,7,9),
              c(11,10,10,12),c(15,13,13,14))
  
  }; if(Peptide[1] == "Q"){
    pPep <- c(CTPath,c(1,8,8,11,11,14,14,15,15,14,14,16,16,18),
              c(9,8,8,10),c(12,11,11,13),c(17,16))
  }
  
  if(Peptide[1] == "R"){
    pPep <- c(CTPath,c(1,8,8,11,11,14,14,17,17,18),c(21,20,20,19,19,17), 
             c(22,20,20,19,19,23),c(24,23,23,25),c(9,8,8,10),
             c(12,11,11,13),c(15,14,14,16))
  
  }; if(Peptide[1] == "S"){
    pPep <- c(CTPath,c(1,8,8,11,11,12),c(9,8,8,10))
  
  }; if(Peptide[1] == "T"){
    pPep <- c(CTPath,c(1,8,8,12,12,13),c(9,8,8,10,10,11),
              c(14,12,12,15))
  }
  
  if(Peptide[1] == "V"){
    pPep <- c(CTPath,c(1,12,12,8,8,11),c(9,8,8,10),
              c(13,12,12,14,14,17),c(15,14,14,16))
  
  }; if(Peptide[1] == "W"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,11,11,17,17,18),c(18,20,20,22),
              c(22,24,24,16,16,17),c(9,8,8,10),c(17,16,16,14,14,15),
              c(13,12,12,14),c(19,18,18,20,20,21),c(23,22,22,24,24,25))
  
  }; if(Peptide[1] == "Y"){
    pPep <- c(CTPath,c(1,8,8,11,11,12,12,14,14,16,16,19),c(19,21,21,11),
              c(11,12,12,13),c(15,14,14,16,16,17,17,18),
              c(20,19,19,21,21,22),c(9,8,8,10))
  }
  
  #store the complete carbon terminus bonding and set up the N for peptide bond
  pPep <- c(pPep,5) 
           #-----------------------------------------#  
  
  MidPath <- c(c(1,2,2,3,3,2),c(6,1,1,4,4,5)) #inner residue bondage
  
  #assign the correct bonding for the inner residues determined by side group
  if(l != 2){
    for(i in 2:(l-1)){
      n.sum <- sum(Pep_lengths[1:(i-1)])  #total length of the previous residues
    
      if(Peptide[i] == "A"){
        pMid <- c(MidPath,c(1,7,7,8),c(9,7,7,10)) 
        
      }; if(Peptide[i] == "C"){
        pMid <- c(MidPath, c(1,7,7,10,10,11),c(8,7,7,9))
        
      } 
        
      if(Peptide[i] == "D"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,10,10,12),c(8,7,7,9))
        
      }; if(Peptide[i] == "E"){
        pMid <- c(MidPath,c(1,7,7,10,10,13,13,14,14,13,13,15),
                  c(8,7,7,9),c(11,10,10,12))
  
      }; if(Peptide[i] == "F"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,13,13,15,15,17,17,19,19,10,10,19,19,20),
                  c(8,7,7,9),c(12,11,11,13,13,14),c(16,15,15,17,17,18))
      }
      
      if(Peptide[i] == "G"){
        pMid <- c(MidPath,c(1,7))
      
      }; if(Peptide[i] == "H"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,13,13,15,15,17,17,10,10,11,11,12),
                  c(8,7,7,9),c(13,14),c(16,15,15,17,17,18))
      
      }; if(Peptide[i] == "I"){
        pMid <- c(MidPath,c(1,11,11,12),c(8,7,7,11,11,13,13,16,16,17),
                  c(9,7,7,10),c(14,13,13,15),c(18,16,16,19))
      }  
      
      if(Peptide[i] == "K"){
        pMid <- c(MidPath,c(1,7,7,10,10,13,13,16,16,19,19,22),c(8,7,7,9), 
                  c(11,10,10,12),c(17,16,16,18),c(20,19,19,21),c(14,13,13,15))
      
      }; if(Peptide[i] == "L"){
        pMid <- c(MidPath,c(1,7,7,14,14,10,10,11),c(8,7,7,9),c(12,10,10,13),
                  c(15,14,14,16,16,18),c(17,16,16,19))
      
      }; if(Peptide[i] == "M"){
        pMid <- c(MidPath,c(1,7,7,10,10,13,13,14,14,15),c(8,7,7,9), 
                  c(11,10,10,12),c(17,14,14,16))
      }
      
      if(Peptide[i] == "N"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,10,10,12,12,13),
                  c(8,7,7,9),c(14,12))
      
      }; if(Peptide[i] == "P"){
        pMid <- c(c(1,2,2,3,3,2),c(5,1,1,4),
                  c(1,6,6,9,9,12,12,4),c(7,6,6,8),
                  c(10,9,9,11),c(14,12,12,13))
        
      }; if(Peptide[i] == "Q"){
        pMid <- c(MidPath,c(1,7,7,10,10,13,13,14,14,13,13,15,15,17),
                  c(8,7,7,9),c(11,10,10,12),c(16,15))
      }
     
      if(Peptide[i] == "R"){
        pMid <- c(MidPath,c(1,7,7,10,10,13,13,16,16,17),c(20,19,19,18,18,16), 
                  c(21,19,19,18,18,22),c(23,22,22,24),c(8,7,7,9),
                  c(11,10,10,12),c(14,13,13,15))
       
      }; if(Peptide[i] == "S"){
        pMid <- c(MidPath,c(1,7,7,10,10,11),c(8,7,7,9))
       
      }; if(Peptide[i] == "T"){
        pMid <- c(MidPath,c(1,7,7,11,11,12),c(8,7,7,9,9,10),
                  c(13,11,11,14))
      }
      
      if(Peptide[i] == "V"){
        pMid <- c(MidPath,c(1,11,11,7,7,10),c(8,7,7,9),
                  c(12,11,11,13,13,16),c(14,13,13,15))
       
      }; if(Peptide[i] == "W"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,10,10,16,16,17),c(17,19,19,21),
                  c(21,23,23,15,15,16),c(8,7,7,9),c(16,15,15,13,13,14),
                  c(12,11,11,13),c(18,17,17,19,19,20),c(22,21,21,23,23,24))
       
      }; if(Peptide[i] == "Y"){
        pMid <- c(MidPath,c(1,7,7,10,10,11,11,13,13,15,15,18),c(18,20,20,10),
                  c(10,11,11,12),c(14,13,13,15,15,16,16,17),
                  c(19,18,18,20,20,21),c(8,7,7,9))
      }
  
      pMid <- pMid + n.sum #assign correct positions
      
      #store the bonding and create peptide bonds
      pPep <- c(pPep,sum(2,n.sum),pMid,sum(4,n.sum)) 
    } 
  }
           #------------------------------------#
  NTPath <- c(c(1,2,2,3,3,2),c(8,1,1,4,4,5),c(6,4,4,7))  #nitrogen terminus bonding
  n.sum <- sum(Pep_lengths[1:l-1])  #length of all previous residues
  
  #assign bonding for the N-Terminus side chain
  if(Peptide[l] == "A"){
    pNT <- c(NTPath,c(1,9,9,10),c(11,9,9,12)) 
  
  }; if(Peptide[l] == "C"){
    pNT <- c(NTPath, c(1,9,9,12,12,13),c(10,9,9,11))
  
  }
  
  if(Peptide[l] == "D"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,12,12,14),c(10,9,9,11))
  
  }; if(Peptide[l] == "E"){
    pNT <- c(NTPath,c(1,9,9,12,12,15,15,16,16,15,15,17),
               c(10,9,9,11),c(14,12,12,13))
  
  }; if(Peptide[l] == "F"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,15,15,17,17,19,19,21,21,12,12,21,21,22),
               c(11,9,9,10),c(14,13,13,15,15,16),c(18,17,17,19,19,20))
  }
  
  if(Peptide[l] == "G"){
    pNT <- c(NTPath,c(1,9))
  
  }; if(Peptide[l] == "H"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,15,15,17,17,19,19,12,12,13,13,14),
              c(11,9,9,10),c(16,15),c(18,17,17,19,19,20))
  
  }; if(Peptide[l] == "I"){
    pNT <- c(NTPath,c(1,13,13,14),c(10,9,9,13,13,15,15,18,18,19),
              c(11,9,9,12),c(16,15,15,17),c(20,18,18,21))
  }
  
  if(Peptide[l] == "K"){
    pNT <- c(NTPath,c(1,9,9,12,12,15,15,18,18,21,21,24),c(11,9,9,10), 
              c(13,12,12,14),c(19,18,18,20),c(22,21,21,23),c(16,15,15,17))
  
  }; if(Peptide[l] == "L"){
    pNT <- c(NTPath,c(1,9,9,16,16,12,12,13),c(11,9,9,10),c(14,12,12,15),
              c(17,16,16,18,18,20),c(19,18,18,21))
  
  }; if(Peptide[l] == "M"){
    pNT <- c(NTPath,c(1,9,9,12,12,15,15,16,16,17),c(11,9,9,10), 
              c(13,12,12,14),c(19,16,16,18))
  }
  
  if(Peptide[l] == "N"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,12,12,14,14,15),
               c(11,9,9,10),c(16,14))
  
  }; if(Peptide[l] == "P"){
    pNT <- c(c(1,2,2,3,3,2),c(7,1,1,4,4,6),
              c(1,8,8,11,11,14,14,4,4,5),c(10,8,8,9),
              c(13,11,11,12),c(15,14,14,16))
  
  }; if(Peptide[l] == "Q"){
    pNT <- c(NTPath,c(1,9,9,12,12,15,15,16,16,15,15,17,17,19),
              c(11,9,9,10),c(14,12,12,13),c(17,18))
  }
  
  if(Peptide[l] == "R"){
    pNT <- c(NTPath,c(1,9,9,12,12,15,15,18,18,19),c(22,21,21,20,20,18), 
             c(23,21,21,20,20,24),c(25,24,24,26),c(11,9,9,10),
             c(14,12,12,13),c(17,15,15,16))
  
  }; if(Peptide[l] == "S"){
    pNT <- c(NTPath,c(1,9,9,12,12,13),c(11,9,9,10))
  
  }; if(Peptide[l] == "T"){
    pNT <- c(NTPath,c(1,9,9,13,13,14),c(10,9,9,11,11,12),
              c(15,13,13,16))
  }
  
  if(Peptide[l] == "V"){
    pNT <- c(NTPath,c(1,13,13,9,9,12),c(11,9,9,10),
              c(14,13,13,15,15,18),c(16,15,15,17))
  
  }; if(Peptide[l] == "W"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,12,12,18,18,19),c(19,21,21,23),
              c(23,25,25,17,17,18),c(11,9,9,10),c(18,17,17,15,15,16),
              c(14,13,13,15),c(20,19,19,21,21,22),c(24,23,23,25,25,26))
  
  }; if(Peptide[l] == "Y"){
    pNT <- c(NTPath,c(1,9,9,12,12,13,13,15,15,17,17,20),c(20,22,22,12),
              c(12,13,13,14),c(16,15,15,17,17,18,18,19),
              c(21,20,20,22,22,23),c(11,9,9,10))
  }
  
  pNT <- pNT + n.sum   #assign correct position
  pPep <- c(pPep,sum(2,n.sum),pNT)  #store the full bonding connections
  
  return(pPep)
}

#-------------------------------------------------#
#-------------------------------------------------#

VizPep = function(AASeq){                             ##visualize the Peptide
  
  l = nchar(AASeq)
  
  Peptide <- strsplit(AASeq,split="")  #convert character string into residues
  Peptide <- unlist(Peptide)
  
  Peptide.atm <- Gen.Peptide(AASeq)
  
  #create a visual representation of the peptide
  gPep <- graph.empty(directed=FALSE) + vertices(unlist(Peptide.atm))
  gPep <- gPep + edges(fPath.Peptide(AASeq))
  
  #assign the correct atom color to the graph
  V.color <- gsub("+","",unlist(Peptide.atm),fixed=TRUE); V.color <- gsub("-","",V.color, fixed = TRUE)
  V.color <- gsub("C","black",V.color); V.color <- gsub("N","blue",V.color); V.color <- gsub("O","red",V.color)
  V.color <- gsub("H","white",V.color); V.color <- gsub("S","gold",V.color)
  V(gPep)$color <- V.color
  
  #plot(gPep, vertex.label.dist = 2, vertex.label.degree = pi)
  #rglplot(gPep, vertex.label.dist = 2, vertex.label.degree = pi)
  tkplot(gPep,vertex.label.dist=0, vertex.label.degree=pi/3)
}

#-------------------------------------------------#
#-------------------------------------------------#

Peptide.atm <- Gen.Peptide(AASeq)
l.PS <- length(unlist(Peptide.atm))
layout<- matrix(c(0,0,0,rnorm(3*(l.PS-1))),ncol=3,byrow=TRUE)

bond.angle <- function(x,y,z,layout){
  n <- layout[x,]
  m <- layout[y,]
  o <- layout[z,]
  layout.z <- o
  
  v = n - m; w = n - o
  n.output <- (v%*%w)/sqrt(sum(v^2)*sum(w^2))
  theta <- acos(n.output)*180/pi
  #print(theta)
  
  attempt = 1
  resets = 0
  while(abs(theta-109.5) > .05){
    
    if(all(o == layout.z) == TRUE){
      weight.layer <- matrix(c(rnorm(30)),10,3)
      bias.layer   <- matrix(c(rnorm(10)),10,1)
      weight.out   <- matrix(c(rnorm(30)),3,10)
      bias.out     <- matrix(c(rnorm(3)),3,1)
    }
    
    o  <-  matrix(o,3,1) 
    a1 <-  tanh(weight.layer%*%o + bias.layer)
    a2 <-  weight.out%*%a1 + bias.out
    
    
    w = n - a2
    n.output <- (v%*%w)/sqrt(sum(v^2)*sum(w^2))
    theta <- acos(n.output)*180/pi
    
    if(abs(theta-109.5) > .05){
      attempt = attempt + 1
      #if(attempt == 751){break}
      
      t <- -1/3*sqrt(sum(v^2))*sqrt(sum(w^2))
      error.output <- as.matrix(t - v%*%w)
      Diag.out     <- matrix(c(rep(1,1)),3,1)
      Diag.layer   <- matrix(c(1-(a1[1])^2,rep(0,10),1-(a1[2])^2,rep(0,10),
                               1-(a1[3])^2,rep(0,10),1-(a1[4])^2,rep(0,10),
                               1-(a1[5])^2,rep(0,10),1-(a1[6])^2,rep(0,10),
                               1-(a1[7])^2,rep(0,10),1-(a1[8])^2,rep(0,10),
                               1-(a1[9])^2,rep(0,10),1-(a1[10])),10,10,byrow=TRUE)
    
      sens.output <- -2*Diag.out %*% error.output
      sens.layer  <- Diag.layer%*%t(weight.out)%*%sens.output
      
      weight.layer <- weight.layer - 0.15*sens.layer%*%t(o)
      bias.layer   <- bias.layer - 0.15*sens.layer
      weight.out   <- weight.out - 0.15*sens.output%*%t(a1)
      bias.out     <- bias.out - 0.15*sens.output
      
      if(sqrt((v[1]-w[1])^2+(v[2]-w[2])^2+(v[3]-w[3])^2) > 10){
        resets = resets + 1
        layout[z,] <- layout.z <- rnorm(3,mean = resets)
        #print(theta)
      }
      o <- layout[z,]
      
      #if(is.integer(attempt/100) == TRUE){
       # layout[y,] <- rnorm(3)
       # m <- layout[y,]
       # v <- n - m
      #}
     # if(is.integer(attempt/25)){print(theta)}
    }
  }
  #print(theta)
  #print(layout[z,])
  return(layout)
}
```


Input Neurons
```{r}
url <- "http://folding.biofold.org/i-mutant//pages/dbMut3D.html"
df <- readHTMLTable(url)
df <- as.data.frame(df[[5]])
colm_names <- as.character(as.matrix(df)[1,])
names(df) <- colm_names
df <- df[3:nrow(df),]
PDB_ids <- as.character(df[,1])
Mutations <- as.character(df[,2])
DDG <- as.numeric(df[,6])
train <- sample(1948,600)
  
Input_Neurons<- function(n){
  # n is a number from 1 to 1948
  
  # N1 neurons
  # First neuron inputs will be pH, Temperature, & AA numerical vector
  
  PDB_ID <- PDB_ids[n]
  mutation <- Mutations[n]
  PDB_file <- getURL( url = paste0("http://www.rcsb.org/pdb/files/",PDB_ID,".pdb"))
  PDB_file <- gsub("[[:space:]]","",PDB_file)  #remove all spaces and gaps
  #Remove all non-essential physiolocial data
  # ^ matches the beginning of a line
  # . matches any character and .* matches any character any number of times
  # $ matches the end of the string
  
  Temperature <- sub("^.*KELVIN):","",PDB_file)
  Temperature <- sub("REMARK.*$","",Temperature)
  Temperature <- as.numeric(Temperature)
  
  pH <- sub("^.*PH:","",PDB_file)
  pH <- sub("REMARK.*$","",pH)
  pH <- as.numeric(pH)

  mutate <- mutate_feature(mutation)
  
  N1 <- c(pH,Temperature,mutate)
  #--------------------------------#
  # N2 neurons
  # Second portion of the input neurons will be
  # characteristic difference between the native
  # and mutated amino acid
  mut <- parse_mutation(mutation)
  phys_native <- num.AAclass(mut$before)
  phys_mutate <- num.AAclass(mut$after)
  N2 <- phys_mutate - phys_native

  Neurons <- c(N1,N2)
  return(Neurons)
}

#something wrong iw
feature_matrix <- sapply(1:1948,Input_Neurons())


  



```


